//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::notified_count_table::Entity as NotifiedCountTable;
pub use super::received_count_table::Entity as ReceivedCountTable;
pub use super::widget_table::Entity as WidgetTable;
