//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "widget_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::notified_count_table::Entity")]
    NotifiedCountTable,
    #[sea_orm(has_many = "super::received_count_table::Entity")]
    ReceivedCountTable,
}

impl Related<super::notified_count_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::NotifiedCountTable.def()
    }
}

impl Related<super::received_count_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ReceivedCountTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
